version: '3'

services:
  mongodb:
    image: mongo:5.0.9
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../src/storage/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: testdb
