name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Instalar dependencias
        run: npm install
        working-directory: ./frontend

      - name: Construir la aplicación
        run: npm run build
        working-directory: ./frontend
