name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Configurar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Instalar dependencias
        run: pnpm install
        working-directory: frontend

      - name: Ejecutar pruebas (opcional, si tienes test configurados)
        run: pnpm test
        working-directory: frontend

      - name: Construir la aplicación
        run: pnpm run build
        working-directory: frontend
